I have decided to claim [[https://en.wikipedia.org/wiki/Email_bankruptcy][Emacs bankruptcy]], not because Emacs is groaning under the weight of all my customizations, but because I feel there is something instructive to be gained from watching someone build up their configuration slowly. I have personally declared 2017 to be "The Year of Structure" in my life, and part of that will be loading my life entirely into Emacs, and writing about it.

Over time, I will likely have to go back and fix earlier entries as I realize mistakes that I've made, so none of these blog entries are immutable. You have been warned. The reason for this is that the primary source material for most posts exists as [[http://orgmode.org/][Org-mode]] files inside my =~/.emacs.d= directory. I am also making the [[https://github.com/fasciism/dot-emacs/][source files]] for this blog publicly available.

Tomorrow's post will contain the core of the Org-to-HTML+Elisp process.

#+BEGIN_SRC emacs-lisp :exports none
  ;;; This block exists solely to prevent errors.
#+END_SRC
