I tend to ignore my Gmail account since I only use it for Google/Android-related things. I should probably pay more attention to it, and so I've decided to add it to my Gnus setup. Whether this is a good idea, or whether it would be preferable to instead forward all email from Gmail to my personal mail server is a problem for Future Me. That guy can handle anything.

#+BEGIN_SRC emacs-lisp
  (add-to-list 'gnus-secondary-select-methods
               '(nnimap "gmail"
                        (nnimap-address "imap.gmail.com")
                        (nnimap-server-port "imaps")
                        (nnimap-stream ssl)
                        (nnmail-expiry-target "nnimap+gmail:[Gmail]/Trash")
                        (nnmail-expiry-wait immediate)))
#+END_SRC

This configuration didn't work for me at first, constantly giving me an authentication error, despite copying-and-pasting my password from my password manager. It turns out that due to my use of two-factor authentication, I needed to create an application-specific password for Gnus to access Gmail. Slightly annoying, but I still highly recommend password managers and two-factor authentication.

I don't have a need to send anything from Gmail, yet, so we'll stick with IMAP for now.

Also, collective nouns amuse me.
